### ISSUE TITLE
Add a Player Database

### ISSUE THREAD

**Issue by plsjustignorethis** [ttgspeed/Sparc#5]
Is there any chance of a player database being added to this? It would be extremely helpful for looking up player information and banning them while they are offline.

**Comment by ttgspeed** [comment]
@DJScias

**Comment by plsjustignorethis** [comment]
Any update on this? The staff team I'm a part of is currently using EPM Rcon and I showed this to a few of them, they loved it all except for the lack of player database.

If you guys don't feel like adding it, could you point me to where in the code it adds players to the list? I could probably write it there. (I'm not experienced in C# very much at all)

**Comment by ttgspeed** [comment]
It's unlikely that it'll be added to the baseline, as Sparc was developed for Asylum, which uses a non-rcon system to maintain a player database.

The code below is where we detect a new player. You can try to implement it yourself there.
https://github.com/ttgspeed/Sparc/blob/master/Sparc/ServerComponent.cs#L437
